name: Generate, Upload, Deploy

on:
  push:
    branches:
      - feature/automation  # Change to your target branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Run Node.js script
      - name: Run matf.js script
        run: |
          node matf.js

      # Upload artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: generated-files
          path: |
            index.html
            matf.css

      # Deploy
      - name: Deploy to Netlify
        run: |
          npx netlify-cli deploy --prod --token ${{ secrets.NETLIFY_TOKEN }} --site matfdraft --dir ./
