name: Generate, Upload, Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Run Node.js script
      - name: Run matf.js script
        run: |
          node matf.js

      # Commit changes
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Add generated index.html

      # Upload artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            index.html
            matf.css

      # Download artifacts to use in deployment
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      # Deploy to Github Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
